<?php
/**
 * This class is a core extension. Implements the functionality to access a 
 * persistence system.
 * 
 * @author Miguel Angel Garcia
 * 
 * Copyright 2012 TAOSMI Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
class eDAL {

    /**
     * The Command Controller object reference.
     */
    private $cmd;

    /**
     * The DAL (Data Access Layer) pool.
     */
    private $DAL = array();

    /**
     * Remember that all the extensions will be initiated with a reference to 
     * the current command controller as unique parameter.
     * 
     * @param cmd  the command controller object reference
     */
    public function __construct (&$cmd) {
        $this->cmd = $cmd;
    }

    /**
     * Gets a DAL module (Data Access Layer) from the pool. If It is not 
     * present in the pool, the DAL module will be loaded automatically.
     * The DAL module must be defined in the application configuration file.
     * 
     * @param DALmodule  a string with the DAL module name
     * @return           a DAL object
     * @throws           EXTException() if the DAL module is not defined 
     * @throws           EXTException() if the DAL module is missing
     */
    public function load ($DALmodule) {
        // Returns the DAL module if it was previously loaded.
        if (isset($this->DAL[$DALmodule])) {
            return $this->DAL[$DALmodule];
        }
        // Loads a new DAL module.
        // Gets the string configuration from the DAL module.
        $DALcfg = $this->cmd->request->get('cfg','DAL');
        if (!isset($DALcfg[$DALmodule])) {
            throw new EXTException('', array(
                'DALmodule' => $DALmodule
            ));
        }
        // Gets the DAL module name and the string configuration.
        list($DALname, $DALstring) = explode(',', $DALcfg[$DALmodule], 2);
        // Gets the DAL file name.
        $DALfile = EXTENSIONS.'/dal/'.$DALname.'.php';
        // If the DAL file is missing, throws an exception.
        if (!file_exists($DALfile)) {
            throw new EXTException('', array(
                'DALmodule' => $DALname,
                'DALfile' => $DALfile
            ));
        }
        // Creates and returns a new DAL object.
        require_once($DALfile);
        $this->DAL[$DALmodule] = new $DALname($DALstring);
        return $this->DAL[$DALmodule];
    }
}

/** 
 * The DAL (Data Access Layer) interface defines the interaction with a 
 * persistence system by setting a basic CRUD functionality (add, remove, 
 * modify, find and get), a transaction control (init, commit and rollback) 
 * and a backup process to be implemented. It is also defined a direct way 
 * to access the persistence system with custom queries.
 * 
 * @author Miguel Angel Garcia
 * 
 * Copyright 2012 TAOSMI Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
interface iDAL {

    /**
     * Checks and parses the DAL (Data Access Layer) connection string.
     * 
     * @param cfg  a string with the connection parameters
     */
    public function __construct ($cfg);

    /**
     * Adds a new item into the persistence system. Returns the primary key or 
     * ID for the new item when autogenerated. Otherwise returns the query result.
     * 
     * @param data  an associative array with the new item data
     * @return      a string with the autogenerated ID for the new item or the query result
     */
    public function add ($data);

    /**
     * Retrieves all the items that matches the options provided. If no options,
     * retrieves all of them.
     * 
     * @param options  an associative array with the filter criteria (optional)
     * @return         an array with the found items or an empty array
     */
    public function find ($options = null);

    /**
     * Sets the target resource into the persistence system.
     * 
     * @param resource  a string with the resource name
     */
    public function from ($resource);

    /**
     * Retrieves an item that matches the unique ID or primary key provided. If 
     * no item matches the primary key, returns false.
     * 
     * @param pk  a string with a unique ID or primary key
     * @return    an associative array with the item data or false
     */
    public function get ($pk);

    /**
     * Modifies the items that matches the options provided with the new data. 
     * If no options, modifies all of them.
     * 
     * @param data     an associative array with the new data
     * @param options  an associative array with the filter criteria (optional)
     * @return         the number of modified items
     */
    public function modify ($data, $options = null);

    /**
     * Executes a custom query directly into the persistence system.
     * 
     * @param query  a string with the query
     * @param fetch  a boolean, if true fetches the query result into an array (optional)
     * @return       a query result or an associative array if fetched
     * @throws       EXTException() if the query fails
     */
     public function query ($query, $fetch = false);

    /**
     * Removes the items that matches the options provided. If no options, 
     * removes all of them.
     * 
     * @param options  an associative array with the filter criteria (optional)
     * @return         the number of removed items
     */
    public function remove ($options = null);

    /**
     * Sets the data that will be retrieved by the find method for each item. 
     * If no data is specified, the find method will retrieve a default set of 
     * data.
     * 
     * @param data  a string with the data to retrieve
     */
    public function select ($data);

    /**
     * Starts a new block of operations to the persistence system. This method 
     * is not mandatory when querying the persistence system.
     */
    public function init ();

    /**
     * Consolidates the changes of the current block of operations to the 
     * persistence system. This method is not mandatory when the init() method 
     * was not used before.
     */
    public function commit ();

    /**
     * Discards the changes of the current block of operations to the 
     * persistence system. This method is not mandatory when querying the 
     * persistence system.
     */
    public function rollback ();

    /**
     * Makes a backup of the entities provided. If no entities, makes a backup 
     * of the whole persistence system.
     * 
     * @param entities  a string with the entities separated by comma (optional)
     * @return          a backup of the entities provided
     */
    public function backup ($entities = null);
}
?>